# Generated by Django 3.0.3 on 2020-02-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
