# Generated by Django 3.0.3 on 2020-02-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200219_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
